const CAR_IMAGES: Record<string, string> = {
  "Renault": "/cars/Renault.jpg",
  "Hyundai": "/cars/Hyundai.jpg",
  "Kia": "/cars/Kia.jpg",
  "Dacia": "/cars/Dacia.jpg",
  "Peugeot": "/cars/Peugeot.jpg",
  "Toyota": "/cars/Toyota.jpg",
  "Volkswagen": "/cars/Volkswagen.jpg",
  "Mercedes": "/cars/Mercedes.jpg",
  "BMW": "/cars/BMW.jpg",
  "Chevrolet": "/cars/Chevrolet.jpg",
  "Nissan": "/cars/Nissan.jpg",
  "MG": "/cars/MG.jpg",
  "Fiat": "/cars/Fiat.jpg",
  "Ford": "/cars/Ford.jpg",
  "Honda": "/cars/Honda.jpg",
  "Mitsubishi": "/cars/Mitsubishi.jpg",
  "Suzuki": "/cars/Suzuki.jpg",
  "Audi": "/cars/Audi.jpg",
  "Jeep": "/cars/Jeep.jpg",
  "Citroën": "/cars/Citroën.jpg",
  "Mazda": "/cars/Mazda.jpg",
  "Opel": "/cars/Opel.jpg",
  "Seat": "/cars/Seat.jpg",
  "Skoda": "/cars/Skoda.jpg",
  "Land Rover": "/cars/Land Rover.jpg",
  "Volvo": "/cars/Volvo.jpg",
  "Porsche": "/cars/Porsche.jpg",
  "Lexus": "/cars/Lexus.jpg",
  "Mini": "/cars/Mini.jpg",
  "Subaru": "/cars/Subaru.jpg",
  "Haval": "/cars/Haval.jpg",
  "Chery": "/cars/Chery.jpg",
  "DFSK": "/cars/DFSK.jpg",
};

export function getCarImage(brand: string): string {
  return CAR_IMAGES[brand] || "";
}
